"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var CityBuilder_1 = require("./CityBuilder");
var FactoryMethod_1 = require("./FactoryMethod");
var EuroBuilder = CityBuilder_1.EuropeanCityBuilder.getInstance();
var AmericanBuilder = CityBuilder_1.AmericanCityBuilder.getInstance();
EuroBuilder.setCity("London");
var london = EuroBuilder.build();
EuroBuilder.setCity("Kyiv");
var kiyv = EuroBuilder.build();
AmericanBuilder.setCity("New-York");
var newYork = AmericanBuilder.build();
var AmericaFactory = FactoryMethod_1.FactoryMethod.createFactory("America");
var EuropeanFactory = FactoryMethod_1.FactoryMethod.createFactory("Europe");
var americanStyleShowTime = AmericaFactory.createShowTime();
var europeanStyleShowTime = EuropeanFactory.createShowTime();
console.log(americanStyleShowTime.showTime(london));
console.log(europeanStyleShowTime.showTime(london));
console.log(americanStyleShowTime.showTime(kiyv));
console.log(europeanStyleShowTime.showTime(kiyv));
console.log(americanStyleShowTime.showTime(newYork));
console.log(europeanStyleShowTime.showTime(newYork));
